### PR TITLE
Allow page size to be set to 0

### LINKED ISSUE #205: Add option to disable candidate list for table engine
### Summary

изображение

i don't need candidate list when using "Translite - Russian (Table)" and i can't found option to disable it

### PR DESCRIPTION
**Pull request by wengxt**
Also, when page size is 0, change some behavior implicitly to allow simulate a
compose table like experience.

Fix #205

### CODE REVIEW

**Comment by kuroya2mouse** [comment]
i has used it with in /home/username/.local/share/fcitx5/ 
[myinputmethod.tar.gz](https://github.com/user-attachments/files/18184543/myinputmethod.tar.gz)

If I need to enter a word that ends in a letter (which used in combination), then I need to press return/enter twice. I disabled the confirmation on return/enter, but I still need to press twice. (Example: most, post)

Also, "ctrl+c" is blocked in the terminal if I do not press enter/arrow left or right/ to "complete" the letter writting

Should I create a separate issue?

**Comment by wengxt** [comment]
@kuroya2mouse thank you for testing! Actually I did fixed that but I forgot to push it. Would you mind give it a try again?

**Comment by wengxt** [comment]
@kuroya2mouse  Also, I suggest you to set PreeditCursorPositionAtBeginning to false. That should make it feel more natural.

**Comment by kuroya2mouse** [comment]
IT'S REALLY WORKS. THANKS THANKS THANKS THANKS THANKS

**Pull request merged**
